/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TimeSlot = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'hostUsername' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
  'bookerUsername' : IDL.Opt(IDL.Text),
  'courtType' : IDL.Text,
});

export const idlService = IDL.Service({
  'bookSlot' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'cancelBooking' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'cancelSlotAsHost' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'createTimeSlot' : IDL.Func([TimeSlot], [IDL.Nat], []),
  'deleteTimeSlot' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'editTimeSlot' : IDL.Func([IDL.Nat, IDL.Text, TimeSlot], [], []),
  'getAllTimeSlots' : IDL.Func([], [IDL.Vec(TimeSlot)], ['query']),
  'getSlotsByUsername' : IDL.Func([IDL.Text], [IDL.Vec(TimeSlot)], ['query']),
  'getProfileComment' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'setProfileComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TimeSlot = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'hostUsername' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
    'bookerUsername' : IDL.Opt(IDL.Text),
    'courtType' : IDL.Text,
  });
  
  return IDL.Service({
    'bookSlot' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'cancelBooking' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'cancelSlotAsHost' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'createTimeSlot' : IDL.Func([TimeSlot], [IDL.Nat], []),
    'deleteTimeSlot' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'editTimeSlot' : IDL.Func([IDL.Nat, IDL.Text, TimeSlot], [], []),
    'getAllTimeSlots' : IDL.Func([], [IDL.Vec(TimeSlot)], ['query']),
    'getSlotsByUsername' : IDL.Func([IDL.Text], [IDL.Vec(TimeSlot)], ['query']),
    'getProfileComment' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'setProfileComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
