/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface TimeSlot {
  'id' : bigint,
  'status' : string,
  'date' : string,
  'time' : string,
  'hostUsername' : string,
  'durationMinutes' : bigint,
  'notes' : [] | [string],
  'location' : string,
  'bookerUsername' : [] | [string],
  'courtType' : string,
}
export interface _SERVICE {
  'bookSlot' : ActorMethod<[bigint, string], undefined>,
  'cancelBooking' : ActorMethod<[bigint, string], undefined>,
  'cancelSlotAsHost' : ActorMethod<[bigint, string], undefined>,
  'createTimeSlot' : ActorMethod<[TimeSlot], bigint>,
  'deleteTimeSlot' : ActorMethod<[bigint, string], undefined>,
  'editTimeSlot' : ActorMethod<[bigint, string, TimeSlot], undefined>,
  'getAllTimeSlots' : ActorMethod<[], Array<TimeSlot>>,
  'getSlotsByUsername' : ActorMethod<[string], Array<TimeSlot>>,
  'getProfileComment' : ActorMethod<[string], [] | [string]>,
  'setProfileComment' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
