/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TimeSlot {
    id: bigint;
    status: string;
    date: string;
    time: string;
    hostUsername: string;
    durationMinutes: bigint;
    notes?: string;
    location: string;
    bookerUsername?: string;
    courtType: string;
}
export interface backendInterface {
    bookSlot(slotId: bigint, bookerUsername: string): Promise<void>;
    createTimeSlot(slot: TimeSlot): Promise<bigint>;
    deleteTimeSlot(slotId: bigint, hostUsername: string): Promise<void>;
    editTimeSlot(slotId: bigint, hostUsername: string, updatedSlot: TimeSlot): Promise<void>;
    getAllTimeSlots(): Promise<Array<TimeSlot>>;
    getSlotsByUsername(username: string): Promise<Array<TimeSlot>>;
}
import type { TimeSlot as _TimeSlot } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async bookSlot(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bookSlot(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookSlot(arg0, arg1);
            return result;
        }
    }
    async createTimeSlot(arg0: TimeSlot): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTimeSlot(to_candid_TimeSlot_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTimeSlot(to_candid_TimeSlot_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteTimeSlot(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTimeSlot(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTimeSlot(arg0, arg1);
            return result;
        }
    }
    async editTimeSlot(arg0: bigint, arg1: string, arg2: TimeSlot): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editTimeSlot(arg0, arg1, to_candid_TimeSlot_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editTimeSlot(arg0, arg1, to_candid_TimeSlot_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async getAllTimeSlots(): Promise<Array<TimeSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTimeSlots();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTimeSlots();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSlotsByUsername(arg0: string): Promise<Array<TimeSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSlotsByUsername(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSlotsByUsername(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_TimeSlot_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimeSlot): TimeSlot {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    date: string;
    time: string;
    hostUsername: string;
    durationMinutes: bigint;
    notes: [] | [string];
    location: string;
    bookerUsername: [] | [string];
    courtType: string;
}): {
    id: bigint;
    status: string;
    date: string;
    time: string;
    hostUsername: string;
    durationMinutes: bigint;
    notes?: string;
    location: string;
    bookerUsername?: string;
    courtType: string;
} {
    return {
        id: value.id,
        status: value.status,
        date: value.date,
        time: value.time,
        hostUsername: value.hostUsername,
        durationMinutes: value.durationMinutes,
        notes: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.notes)),
        location: value.location,
        bookerUsername: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.bookerUsername)),
        courtType: value.courtType
    };
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TimeSlot>): Array<TimeSlot> {
    return value.map((x)=>from_candid_TimeSlot_n4(_uploadFile, _downloadFile, x));
}
function to_candid_TimeSlot_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimeSlot): _TimeSlot {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    date: string;
    time: string;
    hostUsername: string;
    durationMinutes: bigint;
    notes?: string;
    location: string;
    bookerUsername?: string;
    courtType: string;
}): {
    id: bigint;
    status: string;
    date: string;
    time: string;
    hostUsername: string;
    durationMinutes: bigint;
    notes: [] | [string];
    location: string;
    bookerUsername: [] | [string];
    courtType: string;
} {
    return {
        id: value.id,
        status: value.status,
        date: value.date,
        time: value.time,
        hostUsername: value.hostUsername,
        durationMinutes: value.durationMinutes,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        location: value.location,
        bookerUsername: value.bookerUsername ? candid_some(value.bookerUsername) : candid_none(),
        courtType: value.courtType
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
